set nocp
set nolist
set nohlsearch
syntax enable
call pathogen#infect()
call pathogen#helptags()
set number
set tabstop=4
set noexpandtab
set textwidth=80
runtime! config/**/*.vim
colorscheme candy
let g:cpp_class_scope_highlight = 1
let g:cpp_experimental_template_highlight = 1
highlight Normal ctermfg=white ctermbg=black
filetype plugin indent off
